import { mkdir, readFile, writeFile, cp, rm } from 'node:fs/promises';

const recipes = JSON.parse(await readFile(new URL('../data/recipes.json', import.meta.url)));
const shopping = JSON.parse(await readFile(new URL('../data/shopping.json', import.meta.url)));
const trip = JSON.parse(await readFile(new URL('../data/trader-joes.json', import.meta.url)));
const root = new URL('../dist/', import.meta.url);
const e = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => `$${value.toFixed(2)}`;
const total = shopping.items.reduce((sum, item) => sum + Math.round(item.price * 100), 0) / 100;
const budget = shopping.items.reduce((sum, item) => sum + (item.omitBudget ? 0 : Math.round((item.budgetPrice ?? item.price) * 100)), 0) / 100;

function page(title, description, path, body) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><title>${e(title)} · chriswiki recipes</title><meta name="description" content="${e(description)}"><link rel="canonical" href="https://recipes.chriswiki.com${path}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="website"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head>
<body><a class="skip" href="#main">Skip to content</a><div class="shell"><header><a class="brand" href="/">chriswiki<span> / recipes</span></a><nav aria-label="Main"><a href="/"${path === '/' ? ' aria-current="page"' : ''}>Recipes</a><a href="/shopping/"${path === '/shopping/' ? ' aria-current="page"' : ''}>Shopping list</a><a href="/trader-joes/"${path === '/trader-joes/' ? ' aria-current="page"' : ''}>Trader Joe’s</a></nav></header><main id="main">${body}</main><footer><span>A personal recipe notebook.</span><a href="https://github.com/christianwilkins/recipes">View source ↗</a></footer></div></body></html>`;
}

await rm(root, { recursive: true, force: true });
await mkdir(root, { recursive: true });
await cp(new URL('../public/', import.meta.url), root, { recursive: true });
async function output(path, html) {
  const dir = new URL(path, root);
  await mkdir(dir, { recursive: true });
  await writeFile(new URL('index.html', dir), html);
}

await output('./', page('Recipes', 'Saved recipes, practical notes, and a shopping list for Polaris, Ohio.', '/', `
<section class="intro"><p class="eyebrow">The recipe notebook</p><h1>Good things<br>to make.</h1><p>Saved recipes, useful notes, and the ingredients to bring them together.</p></section>
${[['Dinner', 'dinners', 'Dinners'], ['Dessert', 'desserts', 'Desserts'], ['Side dish', 'side-dishes', 'Side dishes']].map(([category, id, title]) => {
  const entries = recipes.filter(r => (r.category ?? 'Dessert') === category);
  if (!entries.length) return '';
  return `<section aria-labelledby="${id}"><div class="section-title"><h2 id="${id}">${title}</h2><span>${entries.length} ${entries.length === 1 ? 'recipe' : 'recipes'}</span></div><div class="recipe-index">${entries.map(r => `<article><p class="meta">${e(r.servings)} · ${e(r.category ?? 'No baking')}</p><h3><a href="/${r.slug}/">${e(r.title)} <span aria-hidden="true">↗</span></a></h3><p>${e(r.description)}</p><a class="text-link" href="/${r.slug}/">Make this recipe</a></article>`).join('')}</div></section>`;
}).join('')}
<aside class="shopping-callout"><div><h2>The Trader Joe’s list.</h2><p>Everyday staples, two dinners, freezer backups, and skincare for the Dublin trip.</p></div><a class="button" href="/trader-joes/">Open Trader Joe’s list</a></aside>
<aside class="shopping-callout"><div><h2>One shop for both desserts.</h2><p>Shared ingredients, a checklist, and budget swaps near Polaris.</p></div><a class="button" href="/shopping/">Open shopping list</a></aside>
<section class="archive"><h2>From the archive</h2><p>The original recipes from the repository.</p><div><a href="https://github.com/christianwilkins/recipes/blob/main/korean-beef-bowl.md">Korean beef bowl ↗</a><a href="https://github.com/christianwilkins/recipes/blob/main/mac-and-cheese.md">Three-ingredient mac and cheese ↗</a><a href="https://github.com/christianwilkins/recipes/blob/main/smoothie.md">Smoothie ↗</a></div></section>`));

for (const r of recipes) {
  await output(`${r.slug}/`, page(r.title, r.description, `/${r.slug}/`, `
<a class="back" href="/">← All recipes</a><section class="recipe-heading"><p class="eyebrow">${e(r.category ?? 'Dessert')} · ${e(r.servings)}</p><h1>${e(r.title)}</h1><p>${e(r.description)}</p><p class="meta">${e(r.time)}</p><div class="actions">${r.shopping !== false ? `<a class="button" href="${e(r.shoppingPath ?? '/shopping/')}">Shop ingredients</a>` : ''}<button class="secondary print" hidden>Print recipe</button>${r.source ? `<a href="${e(r.source)}">${e(r.sourceLabel ?? 'Prep with Drew’s reel')} ↗</a>` : ''}</div></section>
<div class="recipe-body"><section><h2>Ingredients</h2><p class="small">For ${e(r.servings)}. Tap to check off as you cook.</p><ul class="ingredients">${r.ingredients.map(([amount,name], i) => `<li><label><input type="checkbox" data-check="${r.slug}-${i}"><span><strong>${e(amount)}</strong> ${e(name)}</span></label></li>`).join('')}</ul></section><section><h2>Method</h2><ol class="steps">${r.steps.map(s => `<li>${e(s)}</li>`).join('')}</ol>${r.methodNote ? `<p class="small">${e(r.methodNote)}</p>` : ''}<div class="notes"><h3>A few useful notes</h3>${r.notes.map(n => `<p>${e(n)}</p>`).join('')}</div>${r.nutrition ? `<p class="small nutrition">${e(r.nutrition)}</p>` : ''}</section></div>`));
}

const rows = shopping.items.map(item => `<li class="shopping-item" data-id="${item.id}" data-price="${item.price}"${item.omitBudget ? ' data-omit-budget="true"' : ''}${item.budgetPrice ? ` data-budget-price="${item.budgetPrice}"` : ''}>
<label><input type="checkbox" data-check="shop-${item.id}"><span class="item-copy"><strong>${e(item.name)}</strong><span>${e(item.needed)}</span></span></label><div class="purchase"><a href="${e(item.url)}" data-buy-original>${e(item.buy)} ↗</a>${item.budgetBuy ? `<a href="${e(item.budgetUrl)}" data-buy-budget hidden>${e(item.budgetBuy)} ↗</a>` : ''}<span class="price" data-display-price>${item.local ? '' : '~'}${money(item.price)}</span><span class="small" data-price-note>${item.local ? 'Local pickup checked' : 'Online estimate'}</span></div>${item.note ? `<p class="item-note">${e(item.note)}</p>` : ''}</li>`).join('');

await output('shopping/', page('Shopping list', 'A combined shopping checklist for protein banana pudding and a Biscoff cheesecake bowl near Polaris, Ohio.', '/shopping/', `
<a class="back" href="/">← All recipes</a><section class="shopping-heading"><p class="eyebrow">Polaris, Ohio · Checked ${shopping.checked}</p><h1>One shop.<br>Two dessert bowls.</h1><p>Enough for one banana pudding and one Biscoff cheesecake bowl. Prices are for full packages, with leftovers.</p></section>
<div class="shop-layout"><aside class="shop-summary"><h2>The basket</h2><p class="total" id="basket-total">${money(total)}</p><p class="small">Estimated cost of unchecked items. Excludes tax and fulfillment fees.</p><label class="budget-toggle" hidden><input type="checkbox" id="budget-mode"><span>Use budget swaps</span></label><p class="small">Skim milk; omit extra vanilla and monk fruit. Both baskets use store-brand wafers and Neufchâtel.</p><p class="small">Budget basket: ${money(budget)}. Already have whey? ${money(budget - shopping.items.find(i => i.id === 'whey').price)}.</p><div class="summary-actions"><button class="secondary" id="reset" hidden>Reset checklist</button><button class="secondary print" hidden>Print list</button></div><p class="small" id="list-status" role="status" aria-live="polite">0 items checked</p><p class="small">Check off what you have or have bought. Saved on this device.</p><noscript><p>The list works without JavaScript; automatic totals and saving need JavaScript enabled.</p></noscript></aside><section aria-label="Ingredients to buy"><ul class="shopping-items">${rows}</ul></section></div>
<section class="store-notes"><h2>Where to buy</h2><p><a href="${shopping.storeUrl}">${e(shopping.store)}</a><br>${e(shopping.address)}</p><p>A practical one-stop choice. Yogurt, whey, both pudding mixes, cookie butter, and vanilla had local pickup available when checked. Other prices are online estimates. Stock and prices can change; pickup and delivery fees depend on the order.</p><p><a href="https://www.aldi.us/store/aldi/products/20249671-friendly-farms-nonfat-plain-greek-yogurt-32-oz">ALDI’s yogurt was listed at $2.79</a>, and <a href="https://www.kroger.com/p/item/0004300020812">Kroger’s cheesecake pudding at $1.50</a>. Those listings were not verified for local pickup. The small savings may not justify another stop. <a href="https://www.target.com/b/biscoff/-/N-y6zaz">Target’s Biscoff listings</a> were slightly more expensive.</p><p class="small">Shopping research dated ${shopping.checked}. These are comparison links, not an order or a reservation. The basket is a practical low-cost option among the listings checked, not a guarantee of the lowest price everywhere.</p></section>`));
const tripCount = trip.groups.reduce((count, group) => count + group.items.length, 0);
await output('trader-joes/', page('Trader Joe’s grocery and skincare list', 'A complete Dublin shopping checklist for staples, beef stuffed sweet potatoes, chicken satay, freezer meals, and skincare.', '/trader-joes/', `
<a class="back" href="/">← All recipes</a>
<section class="shopping-heading"><p class="eyebrow">Dublin, Ohio · ${e(trip.date)}</p><h1>The Trader Joe’s list.</h1><p>Everyday staples, two dinners, freezer backups, and a few skincare basics. A starter haul for roughly one person for a week, with pantry and freezer leftovers.</p><div class="actions"><button class="secondary print" hidden>Print list</button><button class="secondary" id="reset" hidden>Reset checklist</button></div><p class="small">${tripCount} items, including optional extras. Check off what you have or have bought. Saved in this browser; checks do not sync between devices.</p></section>
<div class="shop-layout"><aside class="shop-summary"><h2>Before you shop</h2><p><strong>Already have:</strong> ${e(trip.alreadyHave.join(', '))}.</p><p class="small"><strong>Check at home:</strong> ${e(trip.checkAtHome.join('; '))}.</p><p class="small">Shared ingredients appear once. Limes, rice, yogurt, and cilantro cover both recipes and everyday meals.</p><p class="small">Powdered peanut butter, red curry paste, and dark soy sauce may require another store. Substitutions are listed below.</p><p><a href="/beef-stuffed-sweet-potatoes/">Beef stuffed sweet potatoes</a></p><p><a href="/chicken-satay-rice-bowls/">Chicken satay rice bowls</a></p></aside>
<div>${trip.groups.map(group => `<section aria-labelledby="trip-${e(group.id)}"><div class="section-title"><h2 id="trip-${e(group.id)}">${e(group.title)}</h2></div><ul class="ingredients">${group.items.map(item => `<li><label><input type="checkbox" data-check="tj-2026-09-27-${e(item.id)}"><span><strong>${e(item.name)}</strong> · ${e(item.quantity)}${item.note ? `<br><small>${e(item.note)}</small>` : ''}</span></label>${item.url ? `<a class="small" href="${e(item.url)}">Product details ↗</a>` : ''}</li>`).join('')}</ul></section>`).join('')}</div></div>
<section class="store-notes"><h2>Store and budget notes</h2><p><a href="${e(trip.storeUrl)}">${e(trip.store)}</a><br>${e(trip.address)}</p><p>Prioritize yogurt, dry rice, beans, eggs, and plain frozen vegetables for flexible meals. The prepared bowls are convenience backups. No live inventory or full basket price has been verified; check shelf prices and package labels. Skincare is roughly $30 before tax if you choose all three products, not a quoted store total.</p><h2>Keep skincare simple</h2><p>Morning: rinse, moisturize, then sunscreen. Evening: cleanse and moisturize. Reapply sunscreen every two hours outdoors. A richer fragrance-free cream may suit very dry skin better than a gel. Retinol, vitamin C serum, scrubs, and toners are not included in this starter list.</p><p>Introduce products one at a time and test on a small area for 7–10 days before broader use, following the product directions. <a href="https://www.aad.org/public/everyday-care/skin-care-secrets/prevent-skin-problems/test-skin-care-products">AAD product testing guidance</a> · <a href="https://www.aad.org/public/everyday-care/skin-care-basics/care/skin-care-budget">Simple skincare on a budget</a>.</p><p class="small">Recipe inspiration: <a href="https://www.instagram.com/reel/Ddl58InP2Ws/">Levi Dang’s chicken satay</a>. Skincare references: <a href="https://www.instagram.com/reel/DbTWYgGxSqb/">Jillian Gottlieb and Alex’s product reel</a> and <a href="https://www.instagram.com/reel/DduW0KDs473/">Dr. Neera Nathan’s routine reel</a>. This list selects a few basics rather than reproducing every product shown.</p></section>`));
await writeFile(new URL('404.html', root), page('Page not found', 'Find a saved recipe.', '/404', '<section class="intro"><h1>That page is missing.</h1><p><a href="/">Back to the recipes</a></p></section>'));
await writeFile(new URL('robots.txt', root), 'User-agent: *\nAllow: /\nSitemap: https://recipes.chriswiki.com/sitemap.xml\n');
await writeFile(new URL('sitemap.xml', root), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/', ...recipes.map(r=>`/${r.slug}/`), '/shopping/', '/trader-joes/'].map(p=>`<url><loc>https://recipes.chriswiki.com${p}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${recipes.length} recipe pages, the index, shopping lists, and 404 page.`);
